name: angular_analyzer_plugin
version: 0.0.10
description: Dart analyzer plugin for Angular 2+
authors:
  - Konstantin Scheglov <scheglov@google.com>
  - Mike Fairhurst <mfairhurst@google.com>
  - Max Kim <maxkim@google.com>
homepage: https://github.com/dart-lang/angular_analyzer_plugin
environment:
  sdk: '>=1.24.0-dev.1.0'
dependencies:
  analyzer: '^0.31.0-alpha.1'
  plugin: '^0.2.0'
  html: '^0.13.1'
  tuple: '^1.0.1'
  analyzer_plugin: '0.0.1-alpha.0'
  angular_ast: '^0.4.0'
  meta: ^1.0.2
  yaml: ^2.1.2
  crypto: '>=1.1.1 <3.0.0'
dev_dependencies:
  test_reflective_loader: '^0.1.0'
  test: '^0.12.20'
  mockito: '^2.0.2'
