language: dart
sudo: false
dart:
  - dev
cache:
  directories:
    - $HOME/.pub-cache
before_script:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"

  # Checkout everything if we're building the SDK
  - cd ..
  - 'gclient config --spec=''solutions = [ { "name": "sdk", "url": "https://github.com/dart-lang/sdk.git", "deps_file": "DEPS", "managed": False } ]'''
  - gclient sync
  - cd ~
script:
  - ./tools/check_format.sh
  - ./tools/travis.sh
env:
  - PACKAGE=analyzer_plugin
  - PACKAGE=server_plugin

