name: angular_analyzer_server_plugin
version: 0.0.4
description: Dart analyzer server plugin for Angular 2
environment:
  sdk: '>=1.21.0-dev.1.0'
dependencies:
  analyzer: '>=0.25.1 <0.27.0'
  angular_analyzer_plugin:
    path: ../analyzer_plugin
  analysis_server: any
  plugin: '^0.2.0'
dev_dependencies:
  test_reflective_loader: '^0.0.3'
  typed_mock: '^0.0.4'
  unittest: '^0.11.0'
dependency_overrides:
  analyzer:
     path: ../../sdk/pkg/analyzer
  analysis_server:
     path: ../../sdk/pkg/analysis_server
  front_end:
     path: ../../sdk/pkg/front_end
